// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _IMAGE_H
#define _IMAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


LV_IMG_DECLARE(ui_img_0);
LV_IMG_DECLARE(ui_img_1);
LV_IMG_DECLARE(ui_img_2);
LV_IMG_DECLARE(ui_img_3);
LV_IMG_DECLARE(ui_img_4);
LV_IMG_DECLARE(ui_img_5);
LV_IMG_DECLARE(ui_img_6);
LV_IMG_DECLARE(ui_img_7);
LV_IMG_DECLARE(ui_img_8);
LV_IMG_DECLARE(ui_img_9);
LV_IMG_DECLARE(ui_img_10);
LV_IMG_DECLARE(ui_img_11);
LV_IMG_DECLARE(ui_img_12);
LV_IMG_DECLARE(ui_img_13);
LV_IMG_DECLARE(ui_img_14);
LV_IMG_DECLARE(ui_img_15);
LV_IMG_DECLARE(ui_img_16);
LV_IMG_DECLARE(ui_img_17);
LV_IMG_DECLARE(ui_img_18);
LV_IMG_DECLARE(ui_img_19);
LV_IMG_DECLARE(ui_img_20);
LV_IMG_DECLARE(ui_img_21);
LV_IMG_DECLARE(ui_img_22);
LV_IMG_DECLARE(ui_img_23);
LV_IMG_DECLARE(ui_img_24);
LV_IMG_DECLARE(ui_img_25);
LV_IMG_DECLARE(ui_img_26);
LV_IMG_DECLARE(ui_img_27);
LV_IMG_DECLARE(ui_img_28);
LV_IMG_DECLARE(ui_img_29);
LV_IMG_DECLARE(ui_img_30);
LV_IMG_DECLARE(ui_img_31);
LV_IMG_DECLARE(ui_img_32);
LV_IMG_DECLARE(ui_img_33);
LV_IMG_DECLARE(ui_img_34);
LV_IMG_DECLARE(ui_img_35);
LV_IMG_DECLARE(ui_img_36);
LV_IMG_DECLARE(ui_img_37);
LV_IMG_DECLARE(ui_img_38);
LV_IMG_DECLARE(ui_img_99);




#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
