// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "../app/app.h"
#include <stdio.h>


///////////////////// VARIABLES ////////////////////


// SCREEN: ui_home

lv_chart_series_t * ui_Chart3_series_1;
lv_chart_series_t * ui_Chart2_series_1;
lv_chart_series_t * ui_Chart4_series_1;
lv_chart_series_t * ui_Chart5_series_1;
lv_chart_series_t * ui_Chart6_series_1;




void ui_home_screen_init(void);
lv_obj_t * ui_home;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_status;
lv_obj_t * ui_device;
lv_obj_t * ui_devices_status;
lv_obj_t * ui_weather;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label13;
void ui_event_CO2(lv_event_t * e);
lv_obj_t * ui_CO2;
lv_obj_t * ui_Image_co2;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
void ui_event_light(lv_event_t * e);
lv_obj_t * ui_light;
lv_obj_t * ui_Image_light;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
void ui_event_temperature(lv_event_t * e);
lv_obj_t * ui_temperature;
lv_obj_t * ui_Image_temperature;
lv_obj_t * ui_Bar3;
lv_obj_t * ui_Label10;
void ui_event_soil(lv_event_t * e);
lv_obj_t * ui_soil;
lv_obj_t * ui_Image_soil;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
void ui_event_humidity(lv_event_t * e);
lv_obj_t * ui_humidity;
lv_obj_t * ui_Image_humidity;
lv_obj_t * ui_Bar2;
lv_obj_t * ui_Label9;
lv_obj_t * ui_info;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Panel2;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_time_bar;
lv_obj_t * ui_date;
lv_obj_t * ui_time;
lv_obj_t * ui_Panel27;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Panel1;
void ui_event_Panel6(lv_event_t * e);
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Panel9;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Panel23;
void ui_event_Roller1(lv_event_t * e);
lv_obj_t * ui_Roller1;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Panel24;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Image10;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;
void ui_event_Slider3(lv_event_t * e);
lv_obj_t * ui_Slider3;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Panel25;
lv_obj_t * ui_Panel26;
lv_obj_t * ui_Label27;
void ui_event_Slider2(lv_event_t * e);
lv_obj_t * ui_Slider2;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Panel28;
lv_obj_t * ui_Label32;
void ui_event_Slider5(lv_event_t * e);
lv_obj_t * ui_Slider5;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Panel29;
lv_obj_t * ui_Label33;
void ui_event_Slider6(lv_event_t * e);
lv_obj_t * ui_Slider6;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Panel30;
lv_obj_t * ui_Label35;
void ui_event_Slider7(lv_event_t * e);
lv_obj_t * ui_Slider7;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Panel7;
void ui_event_Panel8(lv_event_t * e);
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Chart3;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Panel12;
void ui_event_Panel13(lv_event_t * e);
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Chart2;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Panel15;
void ui_event_Panel16(lv_event_t * e);
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Chart4;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_Panel18;
void ui_event_Panel19(lv_event_t * e);
lv_obj_t * ui_Panel19;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Chart5;
lv_obj_t * ui_Panel20;
lv_obj_t * ui_Panel21;
void ui_event_Panel22(lv_event_t * e);
lv_obj_t * ui_Panel22;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Chart6;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_720196017[1] = {&ui_img_1656800463};
const lv_img_dsc_t * ui_imgset_685141116[1] = {&ui_img_1287868244};
const lv_img_dsc_t * ui_imgset_725830175[1] = {&ui_img_902424251};
const lv_img_dsc_t * ui_imgset_956837379[1] = {&ui_img_72425762};
const lv_img_dsc_t * ui_imgset_1381829352[1] = {&ui_img_364366452};
const lv_img_dsc_t * ui_imgset_237022447[1] = {&ui_img_1909428037};
const lv_img_dsc_t * ui_imgset_637263430[1] = {&ui_img_213399634};
const lv_img_dsc_t * ui_imgset_105953424[1] = {&ui_img_453075344};
const lv_img_dsc_t * ui_imgset_1703005419[1] = {&ui_img_83633437};
const lv_img_dsc_t * ui_imgset_2049788799[1] = {&ui_img_242428017};
const lv_img_dsc_t * ui_imgset_597939674[1] = {&ui_img_232707142};
const lv_img_dsc_t * ui_imgset_1516266718[1] = {&ui_img_1026557178};
const lv_img_dsc_t * ui_imgset_2097774830[1] = {&ui_img_1895014438};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_CO2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel10, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        co2_select_sql(e);
    }
}
void ui_event_light(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Panel11, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        light_select_sql(e);
    }
}
void ui_event_temperature(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Panel14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        tmp_selsect_sql(e);
    }
}
void ui_event_soil(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Panel20, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        soil_select_sql(e);
    }
}
void ui_event_humidity(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Panel17, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        hum_select_sql(e);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Panel6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Panel5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lora_switch(e);
    }
}
void ui_event_Roller1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lora_set_time(e);
    }
}
void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label26, target, "", "");
        set_backlight(e);
    }
}
void ui_event_Slider3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label28, target, "", "");
        set_volume(e);
    }
}
void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label29, target, "", "");
        mea.soil_up = lv_slider_get_value(target);
        printf("soil_up: %d\n", mea.soil_up);
    }
}
void ui_event_Slider5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label30, target, "", "");
        mea.soil_down = lv_slider_get_value(target);
        printf("soil_down: %d\n", mea.soil_down);
    }
}
void ui_event_Slider6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label34, target, "", "");
        mea.temp_up = lv_slider_get_value(target);
        printf("temp_up: %d\n", mea.temp_up);
    }
}
void ui_event_Slider7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label36, target, "", "");
        mea.temp_down = lv_slider_get_value(target);
        printf("temp_down: %d\n", mea.temp_down);
    }
}
void ui_event_Panel8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Panel10, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Panel13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Panel11, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Panel16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Panel14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Panel19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Panel17, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Panel22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Panel20, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_home_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_home);
}
