// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void co2_select_sql(lv_event_t * e);
void light_select_sql(lv_event_t * e);
void tmp_selsect_sql(lv_event_t * e);
void soil_select_sql(lv_event_t * e);
void hum_select_sql(lv_event_t * e);
void lora_switch(lv_event_t * e);
void lora_set_time(lv_event_t * e);
void set_backlight(lv_event_t * e);
void set_volume(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
