// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_home_screen_init(void)
{
    ui_home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_home, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_home, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_home, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_home, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_home);
    lv_obj_set_width(ui_Panel4, lv_pct(100));
    lv_obj_set_height(ui_Panel4, lv_pct(100));
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_status = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_status, 80);
    lv_obj_set_height(ui_status, 80);
    lv_obj_set_x(ui_status, -60);
    lv_obj_set_y(ui_status, -13);
    lv_obj_set_align(ui_status, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_status, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_status, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_status, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_device = lv_label_create(ui_status);
    lv_obj_set_width(ui_device, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_device, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_device, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_device, "设备状态");
    lv_obj_set_style_text_color(ui_device, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_device, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_device, &ui_font_sonti_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_devices_status = lv_label_create(ui_status);
    lv_obj_set_width(ui_devices_status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_devices_status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_devices_status, 0);
    lv_obj_set_y(ui_devices_status, 5);
    lv_obj_set_align(ui_devices_status, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_devices_status, "离线");
    lv_obj_set_style_text_color(ui_devices_status, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_devices_status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_devices_status, &ui_font_sonti_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_weather, 171);
    lv_obj_set_height(ui_weather, 180);
    lv_obj_set_x(ui_weather, -12);
    lv_obj_set_y(ui_weather, 13);
    lv_obj_set_align(ui_weather, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weather, lv_color_hex(0x75B1C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_weather, lv_color_hex(0x62747F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_weather, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_weather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_weather);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 10);
    lv_obj_set_y(ui_Image3, 0);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_weather);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -10);
    lv_obj_set_y(ui_Label1, 10);
    lv_obj_set_align(ui_Label1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label1, "广州");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_sonti_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_weather);
    lv_obj_set_width(ui_Panel3, 140);
    lv_obj_set_height(ui_Panel3, 70);
    lv_obj_set_x(ui_Panel3, -5);
    lv_obj_set_y(ui_Panel3, 10);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -10);
    lv_obj_set_y(ui_Label2, -10);
    lv_label_set_text(ui_Label2, "降水概率:");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_sonti_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -10);
    lv_obj_set_y(ui_Label11, 10);
    lv_obj_set_align(ui_Label11, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label11, "风速:");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_sonti_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 60);
    lv_obj_set_y(ui_Label16, -10);
    lv_label_set_text(ui_Label16, "0.5%");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_sonti_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 30);
    lv_obj_set_y(ui_Label15, 10);
    lv_obj_set_align(ui_Label15, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label15, "8.4 km/h");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_sonti_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_weather);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "小雨/大雨");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_sonti_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_weather);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, -30);
    lv_obj_set_align(ui_Label13, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label13, "-10~20℃");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_sonti_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_CO2, 120);
    lv_obj_set_height(ui_CO2, 81);
    lv_obj_set_x(ui_CO2, 48);
    lv_obj_set_y(ui_CO2, -13);
    lv_obj_set_align(ui_CO2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_CO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CO2, lv_color_hex(0x6289AD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CO2, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_CO2, lv_color_hex(0x3E4E71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_CO2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CO2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_co2 = lv_img_create(ui_CO2);
    lv_img_set_src(ui_Image_co2, &ui_img_1287868244);
    lv_obj_set_width(ui_Image_co2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_co2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_co2, -10);
    lv_obj_set_y(ui_Image_co2, -10);
    lv_obj_add_flag(ui_Image_co2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_co2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_CO2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label5, "ppm");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_CO2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label6, "60000");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_light = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_light, 120);
    lv_obj_set_height(ui_light, 81);
    lv_obj_set_x(ui_light, 11);
    lv_obj_set_y(ui_light, -13);
    lv_obj_set_align(ui_light, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_light, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_light, lv_color_hex(0x6289AD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_light, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_light, lv_color_hex(0x3E4E71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_light, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_light, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_light = lv_img_create(ui_light);
    lv_img_set_src(ui_Image_light, &ui_img_232707142);
    lv_obj_set_width(ui_Image_light, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_light, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_light, -10);
    lv_obj_set_y(ui_Image_light, -10);
    lv_obj_add_flag(ui_Image_light, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_light, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_light);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label3, "lx");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_light);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label4, "65535");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperature = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_temperature, 58);
    lv_obj_set_height(ui_temperature, 180);
    lv_obj_set_x(ui_temperature, -28);
    lv_obj_set_y(ui_temperature, 13);
    lv_obj_set_align(ui_temperature, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_temperature, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_temperature, lv_color_hex(0x6289AD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_temperature, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_temperature, lv_color_hex(0x3E4E71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_temperature, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_temperature, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_temperature = lv_img_create(ui_temperature);
    lv_img_set_src(ui_Image_temperature, &ui_img_1026557178);
    lv_obj_set_width(ui_Image_temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_temperature, 0);
    lv_obj_set_y(ui_Image_temperature, 10);
    lv_obj_set_align(ui_Image_temperature, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Image_temperature, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_temperature, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bar3 = lv_bar_create(ui_temperature);
    lv_bar_set_value(ui_Bar3, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar3, 10);
    lv_obj_set_height(ui_Bar3, 100);
    lv_obj_set_align(ui_Bar3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0xF78F8F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar3, lv_color_hex(0xF78F8F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0xF78F8F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_temperature);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label10, "25℃");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_sonti_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soil = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_soil, 110);
    lv_obj_set_height(ui_soil, 88);
    lv_obj_set_x(ui_soil, 130);
    lv_obj_set_y(ui_soil, -1);
    lv_obj_set_align(ui_soil, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_soil, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_soil, lv_color_hex(0x6289AD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soil, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_soil, lv_color_hex(0x3E4E71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_soil, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_soil, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_soil = lv_img_create(ui_soil);
    lv_img_set_src(ui_Image_soil, &ui_img_242428017);
    lv_obj_set_width(ui_Image_soil, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_soil, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_soil, -10);
    lv_obj_set_y(ui_Image_soil, -10);
    lv_obj_add_flag(ui_Image_soil, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_soil, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_soil);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label7, "80");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_soil);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label8, "%");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidity = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_humidity, 58);
    lv_obj_set_height(ui_humidity, 180);
    lv_obj_set_x(ui_humidity, 38);
    lv_obj_set_y(ui_humidity, 13);
    lv_obj_set_align(ui_humidity, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_humidity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_humidity, lv_color_hex(0x6289AD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_humidity, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_humidity, lv_color_hex(0x3E4E71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_humidity, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_humidity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_humidity = lv_img_create(ui_humidity);
    lv_img_set_src(ui_Image_humidity, &ui_img_902424251);
    lv_obj_set_width(ui_Image_humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_humidity, 0);
    lv_obj_set_y(ui_Image_humidity, 10);
    lv_obj_set_align(ui_Image_humidity, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Image_humidity, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_humidity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bar2 = lv_bar_create(ui_humidity);
    lv_bar_set_value(ui_Bar2, 70, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 10);
    lv_obj_set_height(ui_Bar2, 100);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x8BB7F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar2, lv_color_hex(0x8BB7F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x8BB7F0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_humidity);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label9, "70%");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_info = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_info, 162);
    lv_obj_set_height(ui_info, 84);
    lv_obj_set_x(ui_info, 13);
    lv_obj_set_y(ui_info, 13);
    lv_obj_set_align(ui_info, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_info, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_info, lv_color_hex(0xA5AB50), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_info, lv_color_hex(0x3C3C28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_info, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_info, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_info);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label17, "基于Lora的果园环\n境信息智能采集系\n统设计");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_sonti_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_info);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 0);
    lv_obj_set_y(ui_Label23, 10);
    lv_obj_set_align(ui_Label23, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label23, "By @lls");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xEC9FF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel2, 50);
    lv_obj_set_height(ui_Panel2, 90);
    lv_obj_set_x(ui_Panel2, 13);
    lv_obj_set_y(ui_Panel2, -2);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_Button3, 40);
    lv_obj_set_height(ui_Button3, 80);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x3560B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button3, &ui_img_83633437, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_bar = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_time_bar, 129);
    lv_obj_set_height(ui_time_bar, 80);
    lv_obj_set_x(ui_time_bar, -12);
    lv_obj_set_y(ui_time_bar, -13);
    lv_obj_clear_flag(ui_time_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_time_bar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time_bar, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_time_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_time_bar);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, 0);
    lv_obj_set_y(ui_date, -2);
    lv_obj_set_align(ui_date, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_date, "2024年4月15日");
    lv_obj_set_style_text_color(ui_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &ui_font_sonti_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_time_bar);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 0);
    lv_obj_set_y(ui_time, 2);
    lv_obj_set_align(ui_time, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_time, "2:07:45");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel27 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel27, 280);
    lv_obj_set_height(ui_Panel27, 120);
    lv_obj_set_align(ui_Panel27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel27, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel27, lv_color_hex(0xF3ADAD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Panel27);
    lv_img_set_src(ui_Image1, &ui_img_72425762);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label31 = lv_label_create(ui_Panel27);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label31, "警告,湿度湿度超过上限!");
    lv_obj_set_style_text_font(ui_Label31, &ui_font_sonti_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_home);
    lv_obj_set_width(ui_Panel5, lv_pct(100));
    lv_obj_set_height(ui_Panel5, lv_pct(100));
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_Panel1, 480);
    lv_obj_set_height(ui_Panel1, 35);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -15);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xE0E1E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel6, 35);
    lv_obj_set_height(ui_Panel6, 35);
    lv_obj_set_x(ui_Panel6, -10);
    lv_obj_set_y(ui_Panel6, 0);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Panel6);
    lv_img_set_src(ui_Image2, &ui_img_453075344);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "设  置");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_sonti_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_Panel9, 100);
    lv_obj_set_height(ui_Panel9, 50);
    lv_obj_set_x(ui_Panel9, -13);
    lv_obj_set_y(ui_Panel9, -70);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Panel9);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 5);
    lv_obj_set_y(ui_Switch1, 0);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_RIGHT_MID);


    ui_Label24 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -12);
    lv_obj_set_y(ui_Label24, 0);
    lv_obj_set_align(ui_Label24, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label24, "开关");
    lv_obj_set_style_text_font(ui_Label24, &ui_font_sonti_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel23 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_Panel23, 100);
    lv_obj_set_height(ui_Panel23, 125);
    lv_obj_set_x(ui_Panel23, -13);
    lv_obj_set_y(ui_Panel23, 21);
    lv_obj_set_align(ui_Panel23, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel23, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller1 = lv_roller_create(ui_Panel23);
    lv_roller_set_options(ui_Roller1, "15s\n30s\n45s\n1min\n2min\n5min\n10min\n30min\n1h\n2h", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_Roller1, 1, LV_ANIM_OFF);
    lv_obj_set_width(ui_Roller1, 100);
    lv_obj_set_height(ui_Roller1, 100);
    lv_obj_set_x(ui_Roller1, 0);
    lv_obj_set_y(ui_Roller1, 18);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Panel23);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 0);
    lv_obj_set_y(ui_Label25, -12);
    lv_obj_set_align(ui_Label25, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label25, "时间间隔");
    lv_obj_set_style_text_font(ui_Label25, &ui_font_sonti_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel24 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_Panel24, 100);
    lv_obj_set_height(ui_Panel24, 225);
    lv_obj_set_x(ui_Panel24, 12);
    lv_obj_set_y(ui_Panel24, 17);
    lv_obj_set_align(ui_Panel24, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Panel24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel24, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_Panel24);
    lv_img_set_src(ui_Image9, &ui_img_1656800463);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image9, -5);
    lv_obj_set_y(ui_Image9, 10);
    lv_obj_set_align(ui_Image9, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_Panel24);
    lv_img_set_src(ui_Image10, &ui_img_1895014438);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image10, 5);
    lv_obj_set_y(ui_Image10, 10);
    lv_obj_set_align(ui_Image10, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider1 = lv_slider_create(ui_Panel24);
    lv_slider_set_value(ui_Slider1, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 10);
    lv_obj_set_height(ui_Slider1, 125);
    lv_obj_set_x(ui_Slider1, 5);
    lv_obj_set_y(ui_Slider1, 22);


    ui_Slider3 = lv_slider_create(ui_Panel24);
    lv_slider_set_value(ui_Slider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 10);
    lv_obj_set_height(ui_Slider3, 125);
    lv_obj_set_x(ui_Slider3, -5);
    lv_obj_set_y(ui_Slider3, 22);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_TOP_RIGHT);


    ui_Label26 = lv_label_create(ui_Panel24);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 5);
    lv_obj_set_y(ui_Label26, -5);
    lv_label_set_text(ui_Label26, "50");

    ui_Label28 = lv_label_create(ui_Panel24);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -5);
    lv_obj_set_y(ui_Label28, -5);
    lv_obj_set_align(ui_Label28, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label28, "0");

    ui_Panel25 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_Panel25, 262);
    lv_obj_set_height(ui_Panel25, 225);
    lv_obj_set_x(ui_Panel25, 0);
    lv_obj_set_y(ui_Panel25, 17);
    lv_obj_set_align(ui_Panel25, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Panel25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel25, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel26 = lv_obj_create(ui_Panel25);
    lv_obj_set_width(ui_Panel26, 230);
    lv_obj_set_height(ui_Panel26, 70);
    lv_obj_set_x(ui_Panel26, -5);
    lv_obj_set_y(ui_Panel26, -13);
    lv_obj_set_align(ui_Panel26, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Panel26);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -13);
    lv_obj_set_y(ui_Label27, -13);
    lv_label_set_text(ui_Label27, "土壤湿度上阈值");
    lv_obj_set_style_text_font(ui_Label27, &ui_font_sonti_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Panel26);
    lv_slider_set_value(ui_Slider2, 90, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 200);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, 0);
    lv_obj_set_y(ui_Slider2, 10);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);


    ui_Label29 = lv_label_create(ui_Panel26);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 0);
    lv_obj_set_y(ui_Label29, -13);
    lv_obj_set_align(ui_Label29, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label29, "90");

    ui_Panel28 = lv_obj_create(ui_Panel25);
    lv_obj_set_width(ui_Panel28, 230);
    lv_obj_set_height(ui_Panel28, 70);
    lv_obj_set_x(ui_Panel28, -5);
    lv_obj_set_y(ui_Panel28, 60);
    lv_obj_set_align(ui_Panel28, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Panel28);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -13);
    lv_obj_set_y(ui_Label32, -13);
    lv_label_set_text(ui_Label32, "土壤湿度下阈值");
    lv_obj_set_style_text_font(ui_Label32, &ui_font_sonti_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider5 = lv_slider_create(ui_Panel28);
    lv_slider_set_value(ui_Slider5, 40, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider5, 200);
    lv_obj_set_height(ui_Slider5, 10);
    lv_obj_set_x(ui_Slider5, 0);
    lv_obj_set_y(ui_Slider5, 10);
    lv_obj_set_align(ui_Slider5, LV_ALIGN_CENTER);


    ui_Label30 = lv_label_create(ui_Panel28);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 0);
    lv_obj_set_y(ui_Label30, -13);
    lv_obj_set_align(ui_Label30, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label30, "40");

    ui_Panel29 = lv_obj_create(ui_Panel25);
    lv_obj_set_width(ui_Panel29, 230);
    lv_obj_set_height(ui_Panel29, 70);
    lv_obj_set_x(ui_Panel29, -5);
    lv_obj_set_y(ui_Panel29, 133);
    lv_obj_set_align(ui_Panel29, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Panel29);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -13);
    lv_obj_set_y(ui_Label33, -13);
    lv_label_set_text(ui_Label33, "温度上阈值");
    lv_obj_set_style_text_font(ui_Label33, &ui_font_sonti_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider6 = lv_slider_create(ui_Panel29);
    lv_slider_set_value(ui_Slider6, 40, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider6) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider6, 200);
    lv_obj_set_height(ui_Slider6, 10);
    lv_obj_set_x(ui_Slider6, 0);
    lv_obj_set_y(ui_Slider6, 10);
    lv_obj_set_align(ui_Slider6, LV_ALIGN_CENTER);


    ui_Label34 = lv_label_create(ui_Panel29);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, 0);
    lv_obj_set_y(ui_Label34, -13);
    lv_obj_set_align(ui_Label34, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label34, "40");

    ui_Panel30 = lv_obj_create(ui_Panel25);
    lv_obj_set_width(ui_Panel30, 230);
    lv_obj_set_height(ui_Panel30, 70);
    lv_obj_set_x(ui_Panel30, -5);
    lv_obj_set_y(ui_Panel30, 206);
    lv_obj_set_align(ui_Panel30, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel30, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_Panel30);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -13);
    lv_obj_set_y(ui_Label35, -13);
    lv_label_set_text(ui_Label35, "温度下阈值");
    lv_obj_set_style_text_font(ui_Label35, &ui_font_sonti_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider7 = lv_slider_create(ui_Panel30);
    lv_slider_set_value(ui_Slider7, 10, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider7) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider7, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider7, 200);
    lv_obj_set_height(ui_Slider7, 10);
    lv_obj_set_x(ui_Slider7, 0);
    lv_obj_set_y(ui_Slider7, 10);
    lv_obj_set_align(ui_Slider7, LV_ALIGN_CENTER);


    ui_Label36 = lv_label_create(ui_Panel30);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 0);
    lv_obj_set_y(ui_Label36, -13);
    lv_obj_set_align(ui_Label36, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label36, "10");

    ui_Dropdown1 = lv_dropdown_create(ui_Panel5);
    lv_dropdown_set_options(ui_Dropdown1, "设备 1\n设备 2\n设备 3");
    lv_obj_set_width(ui_Dropdown1, 100);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, -13);
    lv_obj_set_y(ui_Dropdown1, 8);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Dropdown1, &ui_font_sonti_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Dropdown1, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown1), &ui_font_sonti_14,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_home);
    lv_obj_set_width(ui_Panel10, lv_pct(100));
    lv_obj_set_height(ui_Panel10, lv_pct(100));
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel10, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Panel10);
    lv_obj_set_width(ui_Panel7, 480);
    lv_obj_set_height(ui_Panel7, 35);
    lv_obj_set_x(ui_Panel7, 0);
    lv_obj_set_y(ui_Panel7, -15);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xE0E1E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel8, 35);
    lv_obj_set_height(ui_Panel8, 35);
    lv_obj_set_x(ui_Panel8, -10);
    lv_obj_set_y(ui_Panel8, 0);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Panel8);
    lv_img_set_src(ui_Image4, &ui_img_453075344);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "二氧化碳浓度");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_sonti_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart3 = lv_chart_create(ui_Panel10);
    lv_obj_set_width(ui_Chart3, 420);
    lv_obj_set_height(ui_Chart3, 190);
    lv_obj_set_x(ui_Chart3, 10);
    lv_obj_set_y(ui_Chart3, 10);
    lv_obj_set_align(ui_Chart3, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart3, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart3, 50);
    lv_chart_set_div_line_count(ui_Chart3, 11, 50);
    lv_chart_set_zoom_x(ui_Chart3, 1024);
    lv_chart_set_zoom_y(ui_Chart3, 256);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_PRIMARY_X, 10, 5, 50, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 0, false, 25);
    ui_Chart3_series_1 = lv_chart_add_series(ui_Chart3, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    //static lv_coord_t ui_Chart3_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 10, 9, 90, 89, 56, 34, 26, 0 };
    //lv_chart_set_ext_y_array(ui_Chart3, ui_Chart3_series_1, ui_Chart3_series_1_array);
    lv_obj_set_style_radius(ui_Chart3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Panel11 = lv_obj_create(ui_home);
    lv_obj_set_width(ui_Panel11, lv_pct(100));
    lv_obj_set_height(ui_Panel11, lv_pct(100));
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel11, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_Panel11);
    lv_obj_set_width(ui_Panel12, 480);
    lv_obj_set_height(ui_Panel12, 35);
    lv_obj_set_x(ui_Panel12, 0);
    lv_obj_set_y(ui_Panel12, -15);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xE0E1E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_Panel12);
    lv_obj_set_width(ui_Panel13, 35);
    lv_obj_set_height(ui_Panel13, 35);
    lv_obj_set_x(ui_Panel13, -10);
    lv_obj_set_y(ui_Panel13, 0);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Panel13);
    lv_img_set_src(ui_Image5, &ui_img_453075344);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "光照强度");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_sonti_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart2 = lv_chart_create(ui_Panel11);
    lv_obj_set_width(ui_Chart2, 420);
    lv_obj_set_height(ui_Chart2, 190);
    lv_obj_set_x(ui_Chart2, 10);
    lv_obj_set_y(ui_Chart2, 10);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart2, 50);
    lv_chart_set_div_line_count(ui_Chart2, 11, 50);
    lv_chart_set_zoom_x(ui_Chart2, 1024);
    lv_chart_set_zoom_y(ui_Chart2, 256);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 50, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 0, false, 25);
    ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    //static lv_coord_t ui_Chart2_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 10, 9, 90, 89, 56, 34, 26, 0 };
    //lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);
    lv_obj_set_style_radius(ui_Chart2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Panel14 = lv_obj_create(ui_home);
    lv_obj_set_width(ui_Panel14, lv_pct(100));
    lv_obj_set_height(ui_Panel14, lv_pct(100));
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel14, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_Panel14);
    lv_obj_set_width(ui_Panel15, 480);
    lv_obj_set_height(ui_Panel15, 35);
    lv_obj_set_x(ui_Panel15, 0);
    lv_obj_set_y(ui_Panel15, -15);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0xE0E1E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_Panel15);
    lv_obj_set_width(ui_Panel16, 35);
    lv_obj_set_height(ui_Panel16, 35);
    lv_obj_set_x(ui_Panel16, -10);
    lv_obj_set_y(ui_Panel16, 0);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Panel16);
    lv_img_set_src(ui_Image6, &ui_img_453075344);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Panel15);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "温  度");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_sonti_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart4 = lv_chart_create(ui_Panel14);
    lv_obj_set_width(ui_Chart4, 420);
    lv_obj_set_height(ui_Chart4, 190);
    lv_obj_set_x(ui_Chart4, 10);
    lv_obj_set_y(ui_Chart4, 10);
    lv_obj_set_align(ui_Chart4, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart4, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart4, 50);
    lv_chart_set_div_line_count(ui_Chart4, 11, 50);
    lv_chart_set_zoom_x(ui_Chart4, 1024);
    lv_chart_set_zoom_y(ui_Chart4, 256);
    lv_chart_set_axis_tick(ui_Chart4, LV_CHART_AXIS_PRIMARY_X, 10, 5, 50, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart4, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart4, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 0, false, 25);
    ui_Chart4_series_1 = lv_chart_add_series(ui_Chart4, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    //static lv_coord_t ui_Chart4_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 10, 9, 90, 89, 56, 34, 26, 0 };
    //lv_chart_set_ext_y_array(ui_Chart4, ui_Chart4_series_1, ui_Chart4_series_1_array);
    lv_obj_set_style_radius(ui_Chart4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Panel17 = lv_obj_create(ui_home);
    lv_obj_set_width(ui_Panel17, lv_pct(100));
    lv_obj_set_height(ui_Panel17, lv_pct(100));
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel17, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_Panel17);
    lv_obj_set_width(ui_Panel18, 480);
    lv_obj_set_height(ui_Panel18, 35);
    lv_obj_set_x(ui_Panel18, 0);
    lv_obj_set_y(ui_Panel18, -15);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0xE0E1E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_Panel18);
    lv_obj_set_width(ui_Panel19, 35);
    lv_obj_set_height(ui_Panel19, 35);
    lv_obj_set_x(ui_Panel19, -10);
    lv_obj_set_y(ui_Panel19, 0);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_Panel19);
    lv_img_set_src(ui_Image7, &ui_img_453075344);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "湿  度");
    lv_obj_set_style_text_font(ui_Label21, &ui_font_sonti_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart5 = lv_chart_create(ui_Panel17);
    lv_obj_set_width(ui_Chart5, 420);
    lv_obj_set_height(ui_Chart5, 190);
    lv_obj_set_x(ui_Chart5, 10);
    lv_obj_set_y(ui_Chart5, 10);
    lv_obj_set_align(ui_Chart5, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart5, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart5, 50);
    lv_chart_set_div_line_count(ui_Chart5, 11, 50);
    lv_chart_set_zoom_x(ui_Chart5, 1024);
    lv_chart_set_zoom_y(ui_Chart5, 256);
    lv_chart_set_axis_tick(ui_Chart5, LV_CHART_AXIS_PRIMARY_X, 10, 5, 50, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart5, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart5, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 0, false, 25);
    ui_Chart5_series_1 = lv_chart_add_series(ui_Chart5, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    //static lv_coord_t ui_Chart5_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 10, 9, 90, 89, 56, 34, 26, 0 };
    //lv_chart_set_ext_y_array(ui_Chart5, ui_Chart5_series_1, ui_Chart5_series_1_array);
    lv_obj_set_style_radius(ui_Chart5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Panel20 = lv_obj_create(ui_home);
    lv_obj_set_width(ui_Panel20, lv_pct(100));
    lv_obj_set_height(ui_Panel20, lv_pct(100));
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel20, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel21 = lv_obj_create(ui_Panel20);
    lv_obj_set_width(ui_Panel21, 480);
    lv_obj_set_height(ui_Panel21, 35);
    lv_obj_set_x(ui_Panel21, 0);
    lv_obj_set_y(ui_Panel21, -15);
    lv_obj_set_align(ui_Panel21, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel21, lv_color_hex(0xE0E1E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel21, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel22 = lv_obj_create(ui_Panel21);
    lv_obj_set_width(ui_Panel22, 35);
    lv_obj_set_height(ui_Panel22, 35);
    lv_obj_set_x(ui_Panel22, -10);
    lv_obj_set_y(ui_Panel22, 0);
    lv_obj_set_align(ui_Panel22, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_Panel22);
    lv_img_set_src(ui_Image8, &ui_img_453075344);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_Panel21);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "土壤湿度");
    lv_obj_set_style_text_font(ui_Label22, &ui_font_sonti_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart6 = lv_chart_create(ui_Panel20);
    lv_obj_set_width(ui_Chart6, 420);
    lv_obj_set_height(ui_Chart6, 190);
    lv_obj_set_x(ui_Chart6, 10);
    lv_obj_set_y(ui_Chart6, 10);
    lv_obj_set_align(ui_Chart6, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart6, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart6, 50);
    lv_chart_set_div_line_count(ui_Chart6, 11, 50);
    lv_chart_set_zoom_x(ui_Chart6, 1024);
    lv_chart_set_zoom_y(ui_Chart6, 256);
    lv_chart_set_axis_tick(ui_Chart6, LV_CHART_AXIS_PRIMARY_X, 10, 5, 50, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart6, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart6, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 0, false, 25);
    ui_Chart6_series_1 = lv_chart_add_series(ui_Chart6, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    //static lv_coord_t ui_Chart6_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 10, 9, 90, 89, 56, 34, 26, 0 };
    //lv_chart_set_ext_y_array(ui_Chart6, ui_Chart6_series_1, ui_Chart6_series_1_array);
    lv_obj_set_style_radius(ui_Chart6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_add_event_cb(ui_CO2, ui_event_CO2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_light, ui_event_light, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_temperature, ui_event_temperature, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_soil, ui_event_soil, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_humidity, ui_event_humidity, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel6, ui_event_Panel6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Roller1, ui_event_Roller1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider3, ui_event_Slider3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider5, ui_event_Slider5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider6, ui_event_Slider6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider7, ui_event_Slider7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel8, ui_event_Panel8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel13, ui_event_Panel13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel16, ui_event_Panel16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel19, ui_event_Panel19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel22, ui_event_Panel22, LV_EVENT_ALL, NULL);

}
